import Head from "next/head";
import SmsTable from "@/helpers/SmsTable";


export default function Home() {
  return (
    <>
      <Head>
        <title>SMS Archive Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 style={{ textAlign: "center" }}>Firestore SMS Data</h1>
        <SmsTable />
      </div>
    </>
  );
}
